Repository sam2127/CS372-AssignmentOrganizer, pull requests merged in 2020-12, with the labels that each got.

#115 exception handling for index.js
  src/index.js
Labels: bug

#118 Removed Tasks.md
  Tasks.md
Labels: code cleanup

#119 Added Test Cases spreadsheet to the repo
  Test Cases.xlsx
Labels: testing

#120 Removed deb installer and updated ReadMe
  README.md
  package-lock.json
  package.json
Labels: bug
