Repository sam2127/CS372-AssignmentOrganizer, pull requests merged in 2020-11, with the labels that each got.

#100 Settings help page typos
  src/help/assignment_help.html
  src/help/settings_help.html
Labels: documentation

#101 Fixes #97
  src/index.js
Labels: bug

#102 Simplified prevMaxId functionality for assignments
  src/assignment.js
Labels: code cleanup

#104 Updated 3 images to the fit new version.
  src/assets/images/semester/add-button.png
  src/assets/images/semester/add-confirmation.png
  src/assets/images/semester/addsemester-select-term.png
Labels: documentation

#105 Updated some screenshots to reflect changes in UI
  src/assets/images/course/Edit-course.png
  src/assets/images/course/add-course-button.png
  src/assets/images/course/add-course-code.png
  src/assets/images/course/add-course-name.png
  src/assets/images/course/add-course-semester-semester-dropdown.png
  src/assets/images/course/add-course-semester.png
  src/assets/images/course/add-course-success.png
  src/assets/images/course/update-button.png
Labels: documentation

#106 Updated screenshots to show UI changes.
  src/assets/images/assignment/add-assignment-course-field-dropdown.png
  src/assets/images/assignment/add-assignment-course-field.png
  src/assets/images/assignment/add-assignment-file-explorer.png
  src/assets/images/assignment/add-assignment-file-select.png
  src/assets/images/assignment/add-assignment-name-field.png
  src/assets/images/assignment/add-assignment-success.png
  src/assets/images/assignment/opened-file.png
Labels: documentation

#108 Updated Settings change/reset message.
  src/setting.js
Labels: modify user interface

#109 Added app icon and installer script.
  package-lock.json
  package.json
  src/assets/icons/App.icns
  src/assets/icons/App.ico
  src/assets/icons/App.png
Labels: core functional requirement, enhancement

#110 Added app icon credits and open links in external browser.
  src/about.html
  src/index.js
Labels: documentation, enhancement

#111 Fixes #67 and #84
  src/index.js
Labels: code cleanup, enhancement

#113 Update some pictures to reflect new UI changes
  src/assets/images/settings/change-storage-location-permission-dialogue-box.png
  src/assets/images/settings/change-storage-location-success.png
  src/assets/images/settings/reset-storage-location-permission-dialogue-box.png
  src/assets/images/settings/reset-storage-location-success-dialogue-box.png
Labels: documentation

#114 Added a point on home page counters and update home icon picture.
  src/assets/images/home/home-counter.png
  src/assets/images/home/home-icons.png
  src/help.html
Labels: documentation
